ALTER TABLE PIC_FOR.PIC_FOR_CAMPS_FORMULARIS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PIC_FOR.PIC_FOR_CAMPS_FORMULARIS CASCADE CONSTRAINTS;

CREATE TABLE PIC_FOR.PIC_FOR_CAMPS_FORMULARIS
(
  FORCAM_ID                	NUMBER(11)   	NOT NULL,
  FORCAM_ID_FORMULARI      	NUMBER(11)   	NOT NULL,
  FORCAM_CAMP              	VARCHAR2(255 BYTE) NOT NULL,
  FORCAM_TIPUS             	VARCHAR2(255 BYTE) NOT NULL,
  FORCAM_TAMANY            	VARCHAR2(10 BYTE),
  FORCAM_TITOL             	VARCHAR2(1000 BYTE),
  FORCAM_DESCRIPCIO        	VARCHAR2(4000 BYTE),
  FORCAM_ORDRE             	NUMBER(4),
  FORCAM_VALORS_POSIBLES   	VARCHAR2(2000 BYTE),
  FORCAM_VALOR_INICIAL     	VARCHAR2(2000 BYTE),
  FORCAM_OBLIGATORI        	VARCHAR2(1 BYTE) DEFAULT 0 NOT NULL,
  FORCAM_VISIBLE           	VARCHAR2(1 BYTE) DEFAULT 1 NOT NULL,
  FORCAM_PROTEGIT          	VARCHAR2(1 BYTE) DEFAULT 0,
  FORCAM_LINIA             	NUMBER(5)    	DEFAULT 1                 	NOT NULL,
  FORCAM_COLUMNA           	NUMBER(5)    	DEFAULT 1                 	NOT NULL,
  FORCAM_ATRIBUTS          	VARCHAR2(1000 BYTE),
  FORCAM_CREADATE          	DATE,
  FORCAM_CREANOMUSER       	VARCHAR2(50 BYTE),
  FORCAM_LASTDATE          	DATE,
  FORCAM_LASTNOMUSER       	VARCHAR2(50 BYTE),
  FORCAM_CAMP_PLANTILLA    	VARCHAR2(10 BYTE),
  FORCAM_WIDTH_CAMP_PLANTILLA  VARCHAR2(3 BYTE),
  FORCAM_VALIDACIO         	VARCHAR2(1000 BYTE),
  FORCAM_TEXT_VALIDACIO    	VARCHAR2(1000 BYTE),
  FORCAM_VALIDAR           	VARCHAR2(1 BYTE) DEFAULT 0 NOT NULL
)
TABLESPACE PIC
PCTUSED	40
PCTFREE	10
INITRANS   1
MAXTRANS   255
STORAGE	(
        	INITIAL      	64K
        	MINEXTENTS   	1
        	MAXEXTENTS   	UNLIMITED
        	PCTINCREASE  	0
        	FREELISTS    	1
        	FREELIST GROUPS  1
        	BUFFER_POOL  	DEFAULT
       	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
NOMONITORING;


test
